version: '3.8'

services:
  db:
    image: postgres:14
    container_name: bookingkart-db
    restart: always
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: bookingkartdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
  build:
    context: .
    dockerfile: Dockerfile
  container_name: bookingkart-app
  volumes:
    - /root/env/.env:/app/.env
  ports:
    - "8080:8080"
  restart: always



  nginx:
    image: nginx:stable
    container_name: bookingkart-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  postgres-data:
