version: '3.8'

services:
  db:
    image: postgres:14
    container_name: bookingkart-db
    restart: always
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: bookingkartdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookingkart-app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres-data:
