version: "3.8"

services:
  db:
    image: postgres:14
    container_name: bookingkart-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: bookingkart-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - /root/env/.env:/app/.env
    restart: always

  nginx:
    image: nginx:stable
    container_name: bookingkart-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    restart: always

volumes:
  postgres-data:
