name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout репозитория
      uses: actions/checkout@v4

    - name: Установка Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Загрузка зависимостей
      run: go mod download

    - name: Сборка проекта
      run: go build ./cmd/main.go
